#This configuration needs to be in the default repository branch
template: |
  ## Changelog:
  
  ## Pull Requests:

  $CHANGES
categories:
  - title: 'Ansible'
    labels:
      - 'ansible'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🍏 CI & Build'
    labels:
      - 'ci'
      - 'build'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
