package com.babylon.wallet.android.domain.model.behaviours

enum class AssetBehaviour {
    SIMPLE_ASSET,
    SUPPLY_INCREASABLE,
    SUPPLY_DECREASABLE,
    SUPPLY_INCREASABLE_BY_ANYONE,
    SUPPLY_DECREASABLE_BY_ANYONE,
    SUPPLY_FLEXIBLE,
    SUPPLY_FLEXIBLE_BY_ANYONE,
    MOVEMENT_RESTRICTED,
    MOVEMENT_RESTRICTABLE_IN_FUTURE,
    MOVEMENT_RESTRICTABLE_IN_FUTURE_BY_ANYONE,
    INFORMATION_CHANGEABLE,
    INFORMATION_CHANGEABLE_BY_ANYONE,
    REMOVABLE_BY_THIRD_PARTY,
    REMOVABLE_BY_ANYONE,
    FREEZABLE_BY_THIRD_PARTY,
    FREEZABLE_BY_ANYONE,
    NFT_DATA_CHANGEABLE,
    NFT_DATA_CHANGEABLE_BY_ANYONE
}

typealias AssetBehaviours = Set<AssetBehaviour>
