/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.babylon.wallet.android.data.gateway.coreapi

import com.babylon.wallet.android.data.gateway.serialisers.PlaintextMessageContentSerializer
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param type
 */
@Serializable(with = PlaintextMessageContentSerializer::class)
abstract class PlaintextMessageContent {

    @Contextual
    @SerialName(value = "type")
    abstract val type: PlaintextMessageContentType
}
