/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.babylon.wallet.android.data.gateway.coreapi

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param type
 * @param `value` The value of a message that the author decided to provide as a UTF-8 string.
 */
@Serializable
data class StringPlaintextMessageContent(

    @Contextual @SerialName(value = "type")
    override val type: PlaintextMessageContentType,

    /* The value of a message that the author decided to provide as a UTF-8 string. */
    @SerialName(value = "value")
    val `value`: kotlin.String

) : PlaintextMessageContent()
