/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.babylon.wallet.android.data.gateway.coreapi

import com.babylon.wallet.android.data.gateway.serialisers.TransactionMessageSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

/**
 *
 *
 * @param type
 */
@Serializable(with = TransactionMessageSerializer::class)
@JsonClassDiscriminator("type")
sealed class TransactionMessage
