[versions]
androidxCore = "1.12.0"
androidx-lifecycle-runtime-ktx = "2.7.0"
androidx-lifecycle-viewmodel-ktx = "2.7.0"
lifecycleViewModelCompose = "2.7.0"
lifecycelRuntimeCompose = "2.7.0"
compose = "1.6.0"
composeConstraintLayout = "1.1.0-alpha13"
composeActivity = "1.8.2"
composeNavigation = "2.7.6"
material = "1.11.0"
composeMaterial3 = "1.2.0-rc01"
material3WindowSizeClass = "1.1.2"
splash = "1.0.1"
immutableCollections = "0.3.7"
accompanist = "0.32.0"
datastorePreferences = "1.1.0-alpha06"
hilt = "2.50"
hiltNavigation = "1.1.0"
biometricKtx = "1.2.0-alpha05"
coilCompose = "2.5.0"
kotlinxSerialization = "1.6.2"
ret = "v1.0.9"
slip10 = "1.2-snapshot"
crypto = "1.72"
okhttpBom = "5.0.0-alpha.11"
retrofit = "2.9.0"
retrofitKoltinxConverter = "1.0.0"
timber = "5.0.1"
barcode = "17.2.0"
cameraCore = "1.4.0-alpha02"
camera2 = "1.4.0-alpha02"
cameraLifecycle = "1.4.0-alpha02"
cameraView = "1.4.0-alpha02"
rootCheck = "0.1.0"
room = "2.6.1"
junit = "4.13.2"
mockk = "1.13.9"
coroutinesTest = "1.7.3"
mockitoKotlin = "5.1.0"
mockitoInline = "5.2.0"
androidXJunit = "1.1.5"
kotlinTestJunit = "1.9.22"
espresso = "3.5.1"
composeUiTestJunit = "1.6.0"
composeUiTooling = "1.6.0"
ktor = "2.3.6"
slf4j = "2.0.9"
turbine = "1.0.0"
zxing = "3.5.2"
apacheCommonsValidator = "1.7"
jsonAssert = "1.5.1"
firebaseCrashlytics = "18.5.1"

androidApplicationPlugin = "8.2.2"
androidLibraryPlugin = "8.2.2"
kotlinAndroidPlugin = "1.9.22"
kotlinSerializationPlugin = "1.9.22"
kotlinJvmPlugin = "1.9.22"
benManesVersionsPlugin = "0.51.0"
versionCatalogUpdatePlugin = "0.8.4"
googleServicesPlugin = "4.4.0"
firebaseCrashlyticsPlugin = "2.9.9"
hiltPlugin = "2.50"
sonarqubePlugin = "4.4.1.3373"
kspPlugin = "1.9.21-1.0.16"

[libraries]
androidxCore = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime-ktx" }
lifecycleViewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-viewmodel-ktx" }
lifecycleViewModelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewModelCompose" }
lifecycelRuntimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycelRuntimeCompose" }
composeUi = { module = "androidx.compose.ui:ui", version.ref = "compose" }
composeRuntime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
composeFoundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
composeConstraintLayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "composeConstraintLayout" }
composeActivity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
composeNavigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
material = { module = "com.google.android.material:material", version.ref = "material" }
composeMaterial = { module = "androidx.compose.material:material", version.ref = "compose" }
composeMaterial3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
material3WindowSizeClass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3WindowSizeClass" }
splash = { module = "androidx.core:core-splashscreen", version.ref = "splash" }
immutableCollections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "immutableCollections" }
accompanistPagerIndicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanistDrawablePainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanistNavigationAnimation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanistPermissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanistSystemUiController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanistPlaceholder = { module = "com.google.accompanist:accompanist-placeholder", version.ref = "accompanist" }
ktorCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorOkhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktorCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorSerialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktorJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktorLogging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
datastorePreferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltNavigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }
hiltCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
biometricKtx = { module = "androidx.biometric:biometric-ktx", version.ref = "biometricKtx" }
coilCompose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
coilComposeSvg = { module = "io.coil-kt:coil-svg", version.ref = "coilCompose" }
coilComposeGif = { module = "io.coil-kt:coil-gif", version.ref = "coilCompose" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
retAndroid = { module = "com.radixdlt:radix-engine-toolkit-android", version.ref = "ret" }
retKotlin = { module = "com.radixdlt:radix-engine-toolkit-kotlin", version.ref = "ret" }
slip10 = { module = "com.radixdlt:slip10-android", version.ref = "slip10" }
crypto = { module = "org.bouncycastle:bcprov-jdk15to18", version.ref = "crypto" }
okhttpBom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttpBom" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttpInterceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitKoltinxConverter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKoltinxConverter" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
barcode = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcode" }
cameraCore = { module = "androidx.camera:camera-core", version.ref = "cameraCore" }
camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera2" }
cameraLifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraLifecycle" }
cameraView = { module = "androidx.camera:camera-view", version.ref = "cameraView" }
rootCheck = { module = "com.scottyab:rootbeer-lib", version.ref = "rootCheck" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
junit = { module = "junit:junit", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesTest" }
mockitoKotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockitoInline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
androidXJunit = { module = "androidx.test.ext:junit", version.ref = "androidXJunit" }
kotlinTestJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlinTestJunit" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
composeUiTestJunit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeUiTestJunit" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUiTooling" }
composeUiTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
slf4j = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
zxing = { module = "com.google.zxing:core", version.ref = "zxing" }
apacheCommonsValidator = { module = "commons-validator:commons-validator", version.ref = "apacheCommonsValidator" }
jsonAssert = { module = "org.skyscreamer:jsonassert", version.ref = "jsonAssert" }
firebaseCrashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlytics" }
[plugins]
android-application = { id = "com.android.application", version.ref = "androidApplicationPlugin" }
android-library = { id = "com.android.library", version.ref = "androidLibraryPlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroidPlugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerializationPlugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinJvmPlugin" }
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "benManesVersionsPlugin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdatePlugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltPlugin" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqubePlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }