# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

desc "Manual trigger"
lane :manual do
  gradle(task: "assembleDebug")
  latest_release = firebase_app_distribution_get_latest_release(
    app: ENV["FIREBASE_APP_ID"],
  )
  increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })
  gradle(task: "assembleDebug")
  firebase_app_distribution(
    app: ENV["FIREBASE_APP_ID"],
    release_notes: ENV["RELEASE_NOTES"],
    groups: ENV["GROUPS"]
  )
end

desc "Deploy pre-release"
lane :beta do
  firebase_app_distribution(
    app: ENV["FIREBASE_APP_ID"],
    groups: "beta"
  )
end

desc "Deploy release"
lane :release do
  gradle(task: "bundle")
end