name: "Build and deploy"

on:
  pull_request:
  push:
    branches:
      - DO-782-ci-cd

jobs:
  
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Lint"
        run: ./gradlew cleanAssemble

  unit_tests:
    name: "Unit tests"
    runs-on: ubuntu-latest

    needs:
      - lint

    steps:
      - uses: actions/checkout@v2

      - name: "Lint"
        run: ./gradlew cleanAssemble

  snapshot_tests:
    name: "Snapshot tests"
    runs-on: ubuntu-latest

    needs:
      - lint

    steps:
      - uses: actions/checkout@v2

      - name: "Lint"
        run: ./gradlew cleanAssemble

  ui_tests:
    name: "UI tests"
    runs-on: ubuntu-latest

    needs:
      - lint

    steps:
      - uses: actions/checkout@v2

      - name: "Lint"
        run: ./gradlew cleanAssemble

  static_analysis:
    name: "Static analysis"
    runs-on: ubuntu-latest

    needs:
      - unit_tests
      - snapshot_tests
      - ui_tests

    steps:
      - uses: actions/checkout@v2

      - name: "Lint"
        run: ./gradlew cleanAssemble