name: "PR and master"

on:
  pull_request:
  push:
    branches:
      - DO-782-ci-cd

jobs:
  
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Lint"
        run: ./gradlew lintDebug

  unit_tests:
    name: "Unit tests"
    runs-on: ubuntu-latest

    needs:
      - lint

    steps:
      - uses: actions/checkout@v2

      - name: "Lint"
        run: ./gradlew testDebugUnitTest

  snapshot_tests:
    name: "Snapshot tests"
    runs-on: ubuntu-latest

    needs:
      - lint

    steps:
      - uses: actions/checkout@v2

      - name: "Lint"
        run: ./gradlew testDebugUnitTest # JUST A PLACEHOLDER, NEEDS TO BE REPLACED

  ui_tests:
    name: "UI tests"
    runs-on: ubuntu-latest

    needs:
      - lint

    steps:
      - uses: actions/checkout@v2

      - name: "Lint"
        run: ./gradlew testDebugUnitTest # JUST A PLACEHOLDER, NEEDS TO BE REPLACED

  static_analysis:
    name: "Static analysis"
    runs-on: ubuntu-latest

    continue-on-error: true

    needs:
      - unit_tests
      - snapshot_tests
      - ui_tests

    steps:
      - uses: actions/checkout@v2

      - name: "Lint"
        run: ./gradlew detektMain

  build_pr:
    if: ${{ github.event.name == 'pull_request' }}

    name: "Build PR"
    runs-on: ubuntu-latest

    needs:
      - static_analysis

    steps:
      - uses: actions/checkout@v2

      - name: "Lint"
        run: ./gradlew assemble

  # deploy_master:
  #   if: |
  #     ${{ github.ref == 'refs/heads/main' }} ||
  #     ${{ github.ref == 'refs/heads/DO-782-ci-cd' }}

  #   name: "Firebase upload"
  #   runs-on: ubuntu-latest

  #   needs:
  #     - static_analysis

  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: ruby/setup-ruby@v1.114.0
  #       with:
  #         ruby-version: '2.7.2'

  #     - uses: maierj/fastlane-action@v2.2.1
  #       with:
  #         lane: 'beta'