name: "Release"

on:
  release:
    types:
      - released

jobs:
  
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Lint"
        run: ./gradlew cleanAssemble