name: Release Drafter
on:
 push:
   # branches to consider in the event; optional, defaults to all
   branches:
     - main
jobs:
 update_release_draft:
   runs-on: ubuntu-latest
   steps:
     - uses: RDXWorks-actions/release-drafter@master
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}