name: "Manual trigger to distribute"

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: "(Optional) Release notes for version you want to distribute"
        required: false
        default: ''
      groups:
        description: "(Optional) Name of the group you want to notify about new version"
        required: false
        default: 'no'
        type: choice
        options:
          - "internal"
          - "no"

jobs:

  deployy:

    name: "Build and distribute"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          token: ${{ secrets.RADIX_BOT_PAT }}

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@516dbb0c760f39b4cdd750ae095f1688780f68f4

      - name: Download Ruby (action)
        uses: ruby/setup-ruby@c7079efafd956afb5d823e8999c2506e1053aefa
        with:
          ruby-version: '3.1.2'
          bundler-cache: true

      - name: Decode Service account credentials
        uses: timheuer/base64-to-file@48657ba25c726c2e3dcf02efa3639fff9b3d587e
        id: firebase_keystore
        with:
          fileName: "service_account.json"
          encodedString: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE_64 }}

      # - uses: oleksiyrudenko/gha-git-credentials@v2.1.1
      #   with:
      #     global: false
      #     name: ${{ secrets.RADIX_BOT_USERNAME }}
      #     actor: ${{ secrets.RADIX_BOT_USERNAME }}
      #     token: ${{ secrets.RADIX_BOT_PAT }}

      - name: Build and distribute
        run: |
          if [ "$GROUPS" == "no" ]; then
            GROUPS=''
          fi
          git config user.name $GIT_USER
          git config user.email $GIT_USER
          bundle exec fastlane main
          git log
          #git push https://${{ secrets.RADIX_BOT_USERNAME }}:${{ secrets.RADIX_BOT_PAT }}@github.com/radixdlt/babylon-wallet-android.git DO-1022-add-manual-trigger
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.firebase_keystore.outputs.filePath }}
          RELEASE_NOTES: ${{ github.event.inputs.release_notes }}
          GROUPS: ${{ github.event.inputs.groups }}
          SLACK_URL: ${{ secrets.SLACK_URL }}
          GIT_USER: ${{ secrets.RADIX_BOT_USERNAME }}